version: "3"
services:
    webapp:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
    webserver:
        build:
            context: .
            dockerfile: DockerfileNginx
        restart: unless-stopped
        ports:
            - "80:80"
        depends_on:
            - webapp
