# Default values for phpfpm-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: bornonthe12th/carbon_offset_scheduler_webapp
  tag: first
  pullPolicy: IfNotPresent
nginxService:
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 80
phpfpmService:
  name: phpfpm
  type: NodePort
  phpfpmPort: 9000
ingress:
  enabled: false
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    - chart-example.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
config:
  nginx.conf: |-
    server {
        listen 80;
        index index.php index.html;
        error_log /var/log/nginx/error.log;
        access_log /var/log/nginx/access.log;
        root /var/www/public;
        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass project-carbon-offset-schedule-phpfpm:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        location /{
            try_files $uri $uri/ /index.php$is_args$args;
            gzip_static on;
        }
    }

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
